ifdef NON_SECURE_FLASH_ADDR
CFLAGS += -DNON_SECURE_FLASH_ADDR=$(NON_SECURE_FLASH_ADDR)
endif

ifdef NON_SECURE_FLASH_END
CFLAGS += -DNON_SECURE_FLASH_END=$(NON_SECURE_FLASH_END)
endif

ifdef NON_SECURE_SRAM_ADDR
CFLAGS += -DNON_SECURE_SRAM_ADDR=$(NON_SECURE_SRAM_ADDR)
endif

ifdef NON_SECURE_SRAM_END
CFLAGS += -DNON_SECURE_SRAM_END=$(NON_SECURE_SRAM_END)
endif

ifdef NSC_ADDR
CFLAGS += -DNSC_ADDR=$(NSC_ADDR)
endif

