# TrustZone memory configuration layout for ARM Cortex-M33

NON_SECURE_FLASH_ADDR ?= 0x08040000
NON_SECURE_FLASH_END  ?= 0x0807FFFF
NON_SECURE_SRAM_ADDR  ?= 0x20030000
NON_SECURE_SRAM_END   ?= 0x2003FFFF
NSC_ADDR              ?= 0x08030000

CFLAGS += -DNON_SECURE_FLASH_ADDR=$(NON_SECURE_FLASH_ADDR)
CFLAGS += -DNON_SECURE_FLASH_END=$(NON_SECURE_FLASH_END)
CFLAGS += -DNON_SECURE_SRAM_ADDR=$(NON_SECURE_SRAM_ADDR)
CFLAGS += -DNON_SECURE_SRAM_END=$(NON_SECURE_SRAM_END)
CFLAGS += -DNSC_ADDR=$(NSC_ADDR)
