name: Compilation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install toolchain
      run: sudo apt install git gcc-arm-none-eabi make gcc-multilib libstdc++-arm-none-eabi-newlib openocd gdb-multiarch doxygen wget unzip python3-serial
    - name: make riot dir
      run: mkdir ../RIOT
    - name: clone RIOT
      run: git clone https://github.com/doaads/RIOT ../RIOT --depth 1 
    - name: make
      run: make BOARD=nucleo-l552ze-q
